name: Lint
on: { push: { branches: [ main ] }, pull_request: { branches: [ main ] } }

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - { name: Checkout, uses: actions/checkout@v4 }
    - { name: Setup Node.js environment, uses: actions/setup-node@v4, with: { node-version: ^18 || >=20 } }
    - { name: Setup pnpm, uses: pnpm/action-setup@v3, with: { version: ^8.15.7, run_install: true } }
    - run: PATH=$PWD/node_modules/.bin:$PATH scripts/lint.sh
