name: Lint
on: { push: { branches: [ main ] }, pull_request: { branches: [ main ] } }

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.2
    - { name: Setup Node.js environment, uses: actions/setup-node@v3.1.1, with: { node-version: ">=18" } }
    - { name: Setup PNPM, uses: pnpm/action-setup@v2.2.1, with: { version: 8, run_install: true } }
    - run: pnpm lint
