name: Test
on: { push: { branches: [ "*" ] }, pull_request: { branches: [ "*" ] } }

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - { name: Checkout, uses: actions/checkout@v4 }
    - { name: Setup Node.js environment, uses: actions/setup-node@v4, with: { node-version: ^18 || >=20 } }
    - { name: Setup pnpm, uses: pnpm/action-setup@v3, with: { version: ^9.0.1, run_install: true } }
    - run: export PATH=$PWD/node_modules/.bin:$PATH
    - run: scripts/package.sh
    - run: scripts/lint.sh
    - run: vitest run
